# Nightfox Alacritty Colors
# Style: nightfox
[colors]
foreground = "#CDCECF"
background = "#192330"
cursor_bg = "#CDCECF"
cursor_border = "#CDCECF"
cursor_fg = "#192330"
selection_bg = "#283648"
selection_fg = "#CDCECF"
ansi = ["#141C26", "#D6616B", "#81B29A", "#dbc074", "#719cd6", "#9D79D6", "#63cdcf", "#dfdfe0"]
brights = ["#7f8c98", "#D6616B", "#58cd8b", "#FFE37E", "#84CEE4", "#B8A1E3", "#59F0FF", "#F2F2F2"]
  